version: '3.5'

services: 
  database:
    image: mongo:latest
    container_name: database
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=${DB_NAME}
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./mongoinit.js:/docker-entrypoint-initdb.d/mongoinit.js:ro
      - mongo-data:/home/app/data
    networks: 
      main:
        aliases: 
          - database
    ports: 
      - "${DB_PORT}:27017"
  backend:
    build: 
      context: ./Backend
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    depends_on: 
      - database
    environment:
      - DBPORT=${DB_PORT}
      - DBNAME=${DB_NAME}
      - DBNETWORK=database
      - DBUSERNAME=${DB_USER}
      - DBPASSWORD=${DB_PASSWORD}
      - PORT=${BACKEND_PORT}
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}}
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    networks: 
      main:
        aliases: 
          - backend
  groupserver:  
    build: 
      context: ./GroupsImageServer
      dockerfile: Dockerfile
    container_name: groupserver
    restart: always
    depends_on: 
      - database
    environment:
      - DBPORT=${DB_PORT}
      - DBNAME=${DB_NAME}
      - DBNETWORK=database
      - DBUSERNAME=${DB_USER}
      - DBPASSWORD=${DB_PASSWORD}
      - PORT=${IMAGESERVER_PORT}
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}}
    ports:
      - ${IMAGESERVER_PORT}:${IMAGESERVER_PORT}
    networks: 
      main:
        aliases: 
          - groupserver
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    depends_on:
      - backend
      - groupserver
      - database
    environment:
      - REACT_APP_BACKEND_URL=${REACT_APP_BACKEND_URL}
      - REACT_APP_GROUPSERVER_URL=${REACT_APP_GROUPSERVER_URL}
    ports: 
      - 80:81
    networks:
      main:
        aliases: 
          - frontend
volumes:
  mongo-data:
    external: true
    name: mongo-data
networks: 
  main:
    