version: '3.5'

services: 
  database:
    image: mongo:latest
    container_name: database
    restart: always
    volumes:
      - mongo-data:/home/app/data
    networks: 
      main:
        aliases: 
          - database
    ports: 
      - "27017:27017"
  backend:
    build: 
      context: ./Backend
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    depends_on: 
      - database
    ports:
      - 8080:8080
    networks: 
      main:
        aliases: 
          - backend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    ports: 
      - 3000:3000
    networks:
      main:
        aliases: 
          - frontend
volumes:
  mongo-data:
    external: true
    name: mongo-data
networks: 
  main:
    