version: '3.5'

services: 
  database:
    image: mongo:latest
    container_name: database
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME: admin
      - MONGO_INITDB_DATABASE: pmdb
      - MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongo-data:/home/app/data
    networks: 
      main:
        aliases: 
          - database
    ports: 
      - "27017:27017"
  backend:
    build: 
      context: ./Backend
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    depends_on: 
      - database
    environment:
      - DBPORT: 27017
      - DBNAME: pmdb
      - DBAUTHENTICATIONREQUIRED: true 
      - DBUSERNAME: admin
      - DBPASSWORD: password
      - PORT: 8082
      - ACCESS_TOKEN_SECRET: place_new_token_here
    ports:
      - 8082:8082
    networks: 
      main:
        aliases: 
          - backend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    ports: 
      - 3000:3000
    networks:
      main:
        aliases: 
          - frontend
volumes:
  mongo-data:
    external: true
    name: mongo-data
networks: 
  main:
    